/*
 * GENERATED by tools/wix-docs-pipeline -- do not edit.
 *
 * Reproduces dev.wix.com's "Show deprecated items" toggle.
 *
 * Differences from the portal, both deliberate:
 *   - state lives in localStorage rather than a cookie, since there is no
 *     server here to read one;
 *   - flipping it does not reload. The portal reloads because its filtering
 *     happens during render; ours is a class on <html>, so it applies
 *     instantly.
 */
(function () {
  'use strict';

  var ON_CLASS = 'wix-show-deprecated';
  var STORAGE_KEY = 'wix-docs-deprecation-mode';
  var MANIFEST = {
  "routes": [
    "/api-reference/assets/media/media-manager/files/bulk-import-files",
    "/api-reference/assets/media/media-manager/files/update-file",
    "/api-reference/assets/pro-gallery/delete-gallery-items",
    "/api-reference/business-management/marketing/marketing-tags/delete-marketing-tag",
    "/api-reference/business-management/payments/wix-payments-provider/transactions/accept-dispute",
    "/api-reference/business-management/payments/wix-payments-provider/transactions/add-evidence",
    "/api-reference/business-management/payments/wix-payments-provider/transactions/generate-evidence-upload-url",
    "/api-reference/business-management/payments/wix-payments-provider/transactions/submit-evidence",
    "/api-reference/business-solutions/bookings/staff-members/staff-members/assign-custom-schedule",
    "/api-reference/business-solutions/e-commerce/orders/draft-orders/create-empty-draft-order",
    "/api-reference/business-solutions/e-commerce/orders/order-transactions/on-order-transactions-updated",
    "/api-reference/business-solutions/e-commerce/payments/memberships/memberships-service-plugin/list-eligible-memberships",
    "/api-reference/business-solutions/events/event-management/form/discard-draft",
    "/api-reference/business-solutions/events/event-management/form/publish-draft",
    "/api-reference/business-solutions/events/registration/ticketing/orders/cancel-reservation",
    "/api-reference/business-solutions/events/registration/ticketing/orders/create-reservation",
    "/api-reference/business-solutions/events/registration/ticketing/orders/on-order-reservation-created",
    "/api-reference/business-solutions/events/registration/ticketing/orders/on-order-reservation-updated",
    "/api-reference/business-solutions/gift-cards/gift-cards/list-gift-cards-by-email",
    "/api-reference/business-solutions/restaurants/online-orders/fulfillment-methods/get-accumulated-fulfillment-methods-availability",
    "/api-reference/business-solutions/restaurants/online-orders/fulfillment-methods/get-combined-method-availability",
    "/api-reference/business-solutions/restaurants/online-orders/operations/delete-operation",
    "/api-reference/crm/loyalty-program/accounts/accounts/list-accounts",
    "/api-reference/crm/members-contacts/members/activity/badges-v4/update-badges-display-order"
  ],
  "groupPrefixes": [
    "/api-reference/business-management/marketing/emails/email-marketing/sender-details/",
    "/api-reference/business-solutions/bookings/calendar/calendar-v1/sessions/",
    "/api-reference/business-solutions/bookings/calendar/schedules-and-sessions/schedule-and-sessions/",
    "/api-reference/business-solutions/bookings/resources/resources-v1/",
    "/api-reference/business-solutions/bookings/services/categories-v1/",
    "/api-reference/business-solutions/bookings/time-slots/availability-calendar/",
    "/api-reference/business-solutions/events/rich-content/",
    "/api-reference/business-solutions/events/rsvp/",
    "/api-reference/business-solutions/forum/category/",
    "/api-reference/business-solutions/forum/post/",
    "/api-reference/business-solutions/pricing-plans/plans-deprecated/",
    "/api-reference/crm/forms/form-v1/",
    "/api-reference/crm/members-contacts/members/activity/badges/"
  ]
};

  var routes = new Set(MANIFEST.routes);
  var prefixes = MANIFEST.groupPrefixes;

  /* Private windows and blocked site data make both of these throw. */
  function isOn() {
    try {
      return window.localStorage.getItem(STORAGE_KEY) === 'true';
    } catch (err) {
      return false;
    }
  }

  function persist(on) {
    try {
      window.localStorage.setItem(STORAGE_KEY, on ? 'true' : 'false');
    } catch (err) {
      /* Session-only is an acceptable degradation; the class still applies. */
    }
  }

  function apply(on) {
    document.documentElement.classList.toggle(ON_CLASS, on);
  }

  function normalise(pathname) {
    return pathname.length > 1 ? pathname.replace(/\/+$/, '') : pathname;
  }

  /* Upstream returns a 404-style empty state for a deprecated URL opened with
   * the toggle off; this is the closest a static site can get. */
  function isDeprecatedRoute(pathname) {
    var route = normalise(pathname);
    if (routes.has(route)) return true;
    for (var i = 0; i < prefixes.length; i++) {
      if (route.indexOf(prefixes[i]) === 0) return true;
    }
    return false;
  }

  function buildToggle() {
    var wrap = document.createElement('div');
    wrap.className = 'wix-deprecation-toggle';

    var input = document.createElement('input');
    input.type = 'checkbox';
    input.id = 'wix-deprecation-toggle-input';
    input.checked = isOn();

    var label = document.createElement('label');
    label.setAttribute('for', input.id);
    label.textContent = 'Show deprecated items';

    input.addEventListener('change', function () {
      persist(input.checked);
      apply(input.checked);
      renderEmptyState();
    });

    wrap.appendChild(input);
    wrap.appendChild(label);
    return wrap;
  }

  /* The navbar is config-driven, so the control has to be inserted next to the
   * links Mintlify rendered from docs.json. */
  function mountToggle() {
    if (document.querySelector('.wix-deprecation-toggle')) return;
    var navbar = document.getElementById('navbar');
    if (!navbar) return;
    var link = navbar.querySelector('.navbar-link');
    var host = link ? link.parentElement : navbar.querySelector('div');
    if (!host) return;
    host.insertBefore(buildToggle(), host.firstChild);
  }

  function renderEmptyState() {
    var existing = document.querySelector('.wix-deprecation-empty-state');
    var shouldShow = !isOn() && isDeprecatedRoute(window.location.pathname);

    if (!shouldShow) {
      if (existing) existing.remove();
      document.documentElement.classList.remove('wix-deprecation-blocked');
      return;
    }
    if (existing) return;

    var content = document.getElementById('content-area') || document.querySelector('main');
    if (!content) return;

    var panel = document.createElement('div');
    panel.className = 'wix-deprecation-empty-state';

    var heading = document.createElement('p');
    heading.className = 'wix-deprecation-empty-state-title';
    heading.textContent = 'This item is deprecated';

    var body = document.createElement('p');
    body.className = 'wix-deprecation-empty-state-body';
    body.textContent =
      'To view deprecated items, enable "Show deprecated items" in the top bar.';

    var action = document.createElement('button');
    action.type = 'button';
    action.className = 'wix-deprecation-empty-state-action';
    action.textContent = 'Show deprecated items';
    action.addEventListener('click', function () {
      persist(true);
      apply(true);
      var input = document.getElementById('wix-deprecation-toggle-input');
      if (input) input.checked = true;
      renderEmptyState();
    });

    panel.appendChild(heading);
    panel.appendChild(body);
    panel.appendChild(action);
    content.appendChild(panel);
    /* CSS hides the real article; the panel sits in its place. */
    document.documentElement.classList.add('wix-deprecation-blocked');
  }

  function sync() {
    apply(isOn());
    mountToggle();
    renderEmptyState();
  }

  apply(isOn());
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', sync);
  } else {
    sync();
  }

  /* Mintlify navigates client-side, so re-run on every route change. */
  ['pushState', 'replaceState'].forEach(function (name) {
    var original = history[name];
    history[name] = function () {
      var result = original.apply(this, arguments);
      window.setTimeout(sync, 0);
      return result;
    };
  });
  window.addEventListener('popstate', function () {
    window.setTimeout(sync, 0);
  });

  /* The navbar and content area are re-rendered on navigation, which drops the
   * injected nodes; re-mount when that happens.
   *
   * Coalesced into one frame: both callbacks insert nodes, which re-enters the
   * observer, and on a sidebar this size an un-debounced handler runs hundreds
   * of times per navigation. Both are idempotent, so the frame's worth of
   * mutations collapses into a single pass. */
  if (window.MutationObserver) {
    var scheduled = false;
    var observer = new MutationObserver(function () {
      if (scheduled) return;
      scheduled = true;
      window.requestAnimationFrame(function () {
        scheduled = false;
        mountToggle();
        renderEmptyState();
      });
    });
    observer.observe(document.body, { childList: true, subtree: true });
  }
})();
